User.create!([
  {email: "admin@gmail.com", name: "Admin", role: "Admin",
    password: "12345678", password_confirmation: "12345678"},
  {email: "letattungtb@gmail.com", name: "Le Tung",
    password: "tung123", password_confirmation: "tung123"}
])
10.times do |n|
  name  = Faker::Name.name
  email = "example-#{n+1}@gmail.com"
  password = "123456"
  User.create!(name: name, email: email, password: password,
    password_confirmation: password)
end
puts "Create Account User"

Category.create!([
  {name: "野菜"},
  {name: "フルーツ"},
  {name: "米・雑穀"},
  {name: "花・茶"}
])
puts "Create Categories"

Product.create!([
  {name: "小松菜", image: Rails.root.join("app/assets/images/products/1.jpg").open, category_id: 1},
  {name: "チンゲン菜", image: Rails.root.join("app/assets/images/products/2.jpg").open, category_id: 1},
  {name: "つららラディッシュ", image: Rails.root.join("app/assets/images/products/3.jpg").open, category_id: 1},
  {name: "ニンジン", image: Rails.root.join("app/assets/images/products/4.jpg").open, category_id: 1},
  {name: "ベビーキャロット", image: Rails.root.join("app/assets/images/products/5.jpg").open, category_id: 1},
  {name: "黒ニンジン", image: Rails.root.join("app/assets/images/products/6.jpg").open, category_id: 1},
  {name: "ホワイトコーン(白くまコーン)", image: Rails.root.join("app/assets/images/products/7.jpg").open, category_id: 1},
  {name: "とうもろこし(黄＆白)", image: Rails.root.join("app/assets/images/products/8.jpg").open, category_id: 1},
  {name: "コシヒカリ(白米)", image: Rails.root.join("app/assets/images/products/9.jpg").open, category_id: 3},
  {name: "コシヒカリ(玄米)", image: Rails.root.join("app/assets/images/products/10.jpg").open, category_id: 3},
  {name: "新之助(白米)", image: Rails.root.join("app/assets/images/products/11.jpg").open, category_id: 3},
  {name: "ベビーキャロット", image: Rails.root.join("app/assets/images/products/5.jpg").open, category_id: 1},
  {name: "新之助(白米)", image: Rails.root.join("app/assets/images/products/12.jpg").open, category_id: 3},
  {name: "ヒノヒカリ(白米)", image: Rails.root.join("app/assets/images/products/13.jpg").open, category_id: 3},
  {name: "ヒノヒカリ(玄米)", image: Rails.root.join("app/assets/images/products/14.jpg").open, category_id: 3},
  {name: "ゆめぴりか(白米)", image: Rails.root.join("app/assets/images/products/15.jpg").open, category_id: 3},
  {name: "ななつぼし(白米)", image: Rails.root.join("app/assets/images/products/16.jpg").open, category_id: 3},
  {name: "ふっくりんこ(白米)", image: Rails.root.join("app/assets/images/products/17.jpg").open, category_id: 3},
  {name: "あきたこまち（白米）", image: Rails.root.join("app/assets/images/products/18.jpg").open, category_id: 3},
  {name: "あきたこまち（玄米）", image: Rails.root.join("app/assets/images/products/19.jpg").open, category_id: 3},
  {name: "松山三井(白米)", image: Rails.root.join("app/assets/images/products/20.jpg").open, category_id: 3},
  {name: "サラダからし菜", image: Rails.root.join("app/assets/images/products/21.jpg").open, category_id: 1},
  {name: "スイスチャード", image: Rails.root.join("app/assets/images/products/22.jpg").open, category_id: 1},
  {name: "だだちゃ豆", image: Rails.root.join("app/assets/images/products/23.jpg").open, category_id: 3},
  {name: "みさを大豆", image: Rails.root.join("app/assets/images/products/24.jpg").open, category_id: 3},
  {name: "鳴門金時", image: Rails.root.join("app/assets/images/products/25.jpg").open, category_id: 1},
  {name: "安納芋", image: Rails.root.join("app/assets/images/products/26.jpg").open, category_id: 1},
  {name: "紅はるか", image: Rails.root.join("app/assets/images/products/27.jpg").open, category_id: 1},
  {name: "紫芋", image: Rails.root.join("app/assets/images/products/28.jpg").open, category_id: 1},
  {name: "ブロッコリー", image: Rails.root.join("app/assets/images/products/29.jpg").open, category_id: 1},
  {name: "スティックセニョール", image: Rails.root.join("app/assets/images/products/30.jpg").open, category_id: 1},
  {name: "エンサイ(空心菜)", image: Rails.root.join("app/assets/images/products/31.jpg").open, category_id: 1},
  {name: "温州みかん", image: Rails.root.join("app/assets/images/products/32.jpg").open, category_id: 2},
  {name: "いよかん", image: Rails.root.join("app/assets/images/products/33.jpg").open, category_id: 1},
  {name: "極早生みかん", image: Rails.root.join("app/assets/images/products/34.jpg").open, category_id: 2},
  {name: "里芋", image: Rails.root.join("app/assets/images/products/35.jpg").open, category_id: 1},
  {name: "つるのこ芋", image: Rails.root.join("app/assets/images/products/36.jpg").open, category_id: 1},
  {name: "なす", image: Rails.root.join("app/assets/images/products/37.jpg").open, category_id: 1},
  {name: "純白なす", image: Rails.root.join("app/assets/images/products/38.jpg").open, category_id: 1},
  {name: "長なす", image: Rails.root.join("app/assets/images/products/39.jpg").open, category_id: 1},
  {name: "ピーマン", image: Rails.root.join("app/assets/images/products/40.jpg").open, category_id: 1},
  {name: "プチピーマン", image: Rails.root.join("app/assets/images/products/41.jpg").open, category_id: 1},
  {name: "万願寺唐辛子", image: Rails.root.join("app/assets/images/products/42.jpg").open, category_id: 1},
  {name: "愛宕柿", image: Rails.root.join("app/assets/images/products/43.jpg").open, category_id: 2},
  {name: "イチジク", image: Rails.root.join("app/assets/images/products/44.jpg").open, category_id: 2},
  {name: "トマト", image: Rails.root.join("app/assets/images/products/45.jpg").open, category_id: 1},
  {name: "ミディトマト", image: Rails.root.join("app/assets/images/products/46.jpg").open, category_id: 1},
  {name: "ミニトマト", image: Rails.root.join("app/assets/images/products/47.jpg").open, category_id: 1},
  {name: "ゼリートマト", image: Rails.root.join("app/assets/images/products/48.jpg").open, category_id: 1},
  {name: "ピオーネ", image: Rails.root.join("app/assets/images/products/49.jpg").open, category_id: 2},
  {name: "シャインマスカット", image: Rails.root.join("app/assets/images/products/50.jpg").open, category_id: 2},
  {name: "パクチー", image: Rails.root.join("app/assets/images/products/51.jpg").open, category_id: 1},
  {name: "レモン", image: Rails.root.join("app/assets/images/products/52.jpg").open, category_id: 1},
  {name: "グリーンレモン", image: Rails.root.join("app/assets/images/products/53.jpg").open, category_id: 2},
  {name: "栗", image: Rails.root.join("app/assets/images/products/54.jpg").open, category_id: 2},
  {name: "マコモダケ", image: Rails.root.join("app/assets/images/products/55.jpg").open, category_id: 1},
  {name: "白ネギ", image: Rails.root.join("app/assets/images/products/56.jpg").open, category_id: 1},
  {name: "山の芋", image: Rails.root.join("app/assets/images/products/57.jpg").open, category_id: 1},
  {name: "黄美香メロン", image: Rails.root.join("app/assets/images/products/58.jpg").open, category_id: 2},
  {name: "ズッキーニ", image: Rails.root.join("app/assets/images/products/59.jpg").open, category_id: 1}
])
puts "Create Products"

Vitamin.create!([
  {name: "カルシウム"},
  {name: "鉄"},
  {name: "ビタミンc"},
  {name: "β-カロテン"},
  {name: "葉酸"},
  {name: "食物繊維"},
  {name: "ナトリウム"},
  {name: "ビタミンA"},
  {name: "たんぱく質"},
  {name: "大豆イソフラボン"},
  {name: "大豆サポニン"},
  {name: "ビタミンB1"},
  {name: "ビタミンE"},
  {name: "ビタミンK"},
  {name: "でんぷん"},
  {name: "ビタミンP"}
])
puts "Create Vitamins"

ProductVitamin.create!([
  {product_id: 1, vitamin_id: 1},
  {product_id: 1, vitamin_id: 2},
  {product_id: 1, vitamin_id: 3},
  {product_id: 1, vitamin_id: 4},
  {product_id: 1, vitamin_id: 5},
  {product_id: 2, vitamin_id: 6},
  {product_id: 2, vitamin_id: 7},
  {product_id: 2, vitamin_id: 8},
  {product_id: 2, vitamin_id: 9},
  {product_id: 2, vitamin_id: 10},
  {product_id: 3, vitamin_id: 11},
  {product_id: 3, vitamin_id: 11},
  {product_id: 3, vitamin_id: 12},
  {product_id: 3, vitamin_id: 13},
  {product_id: 3, vitamin_id: 14},
  {product_id: 4, vitamin_id: 15},
  {product_id: 4, vitamin_id: 16},
  {product_id: 4, vitamin_id: 1},
  {product_id: 4, vitamin_id: 3},
  {product_id: 4, vitamin_id: 5},
  {product_id: 5, vitamin_id: 7},
  {product_id: 5, vitamin_id: 9},
  {product_id: 5, vitamin_id: 11},
  {product_id: 5, vitamin_id: 13},
  {product_id: 5, vitamin_id: 15},
  {product_id: 6, vitamin_id: 2},
  {product_id: 6, vitamin_id: 4},
  {product_id: 6, vitamin_id: 6},
  {product_id: 6, vitamin_id: 8},
  {product_id: 6, vitamin_id: 10},
  {product_id: 7, vitamin_id: 12},
  {product_id: 7, vitamin_id: 14},
  {product_id: 7, vitamin_id: 16},
  {product_id: 7, vitamin_id: 1},
  {product_id: 7, vitamin_id: 2},
  {product_id: 8, vitamin_id: 3},
  {product_id: 8, vitamin_id: 5},
  {product_id: 8, vitamin_id: 8},
  {product_id: 8, vitamin_id: 13},
  {product_id: 8, vitamin_id: 15},
  {product_id: 9, vitamin_id: 7},
  {product_id: 9, vitamin_id: 8},
  {product_id: 9, vitamin_id: 9},
  {product_id: 9, vitamin_id: 10},
  {product_id: 9, vitamin_id: 11},
  {product_id: 10, vitamin_id: 12},
  {product_id: 10, vitamin_id: 13},
  {product_id: 10, vitamin_id: 14},
  {product_id: 10, vitamin_id: 15},
  {product_id: 10, vitamin_id: 16},
  {product_id: 11, vitamin_id: 1},
  {product_id: 11, vitamin_id: 2},
  {product_id: 11, vitamin_id: 3},
  {product_id: 11, vitamin_id: 4},
  {product_id: 11, vitamin_id: 5},
  {product_id: 12, vitamin_id: 6},
  {product_id: 12, vitamin_id: 7},
  {product_id: 12, vitamin_id: 8},
  {product_id: 12, vitamin_id: 9},
  {product_id: 12, vitamin_id: 10},
  {product_id: 13, vitamin_id: 11},
  {product_id: 13, vitamin_id: 11},
  {product_id: 13, vitamin_id: 12},
  {product_id: 13, vitamin_id: 13},
  {product_id: 13, vitamin_id: 14},
  {product_id: 14, vitamin_id: 15},
  {product_id: 14, vitamin_id: 16},
  {product_id: 14, vitamin_id: 1},
  {product_id: 14, vitamin_id: 3},
  {product_id: 14, vitamin_id: 5},
  {product_id: 15, vitamin_id: 7},
  {product_id: 15, vitamin_id: 9},
  {product_id: 15, vitamin_id: 11},
  {product_id: 15, vitamin_id: 13},
  {product_id: 15, vitamin_id: 15},
  {product_id: 16, vitamin_id: 2},
  {product_id: 16, vitamin_id: 4},
  {product_id: 16, vitamin_id: 6},
  {product_id: 16, vitamin_id: 8},
  {product_id: 16, vitamin_id: 10},
  {product_id: 17, vitamin_id: 12},
  {product_id: 17, vitamin_id: 14},
  {product_id: 17, vitamin_id: 16},
  {product_id: 17, vitamin_id: 1},
  {product_id: 17, vitamin_id: 2},
  {product_id: 18, vitamin_id: 3},
  {product_id: 18, vitamin_id: 5},
  {product_id: 18, vitamin_id: 8},
  {product_id: 18, vitamin_id: 13},
  {product_id: 18, vitamin_id: 15},
  {product_id: 19, vitamin_id: 7},
  {product_id: 19, vitamin_id: 8},
  {product_id: 19, vitamin_id: 9},
  {product_id: 19, vitamin_id: 10},
  {product_id: 19, vitamin_id: 11},
  {product_id: 20, vitamin_id: 12},
  {product_id: 20, vitamin_id: 13},
  {product_id: 20, vitamin_id: 14},
  {product_id: 20, vitamin_id: 15},
  {product_id: 20, vitamin_id: 16},
  {product_id: 21, vitamin_id: 1},
  {product_id: 21, vitamin_id: 2},
  {product_id: 21, vitamin_id: 3},
  {product_id: 21, vitamin_id: 4},
  {product_id: 21, vitamin_id: 5},
  {product_id: 22, vitamin_id: 6},
  {product_id: 22, vitamin_id: 7},
  {product_id: 22, vitamin_id: 8},
  {product_id: 22, vitamin_id: 9},
  {product_id: 22, vitamin_id: 10},
  {product_id: 23, vitamin_id: 11},
  {product_id: 23, vitamin_id: 11},
  {product_id: 23, vitamin_id: 12},
  {product_id: 23, vitamin_id: 13},
  {product_id: 23, vitamin_id: 14},
  {product_id: 24, vitamin_id: 15},
  {product_id: 24, vitamin_id: 16},
  {product_id: 24, vitamin_id: 1},
  {product_id: 24, vitamin_id: 3},
  {product_id: 24, vitamin_id: 5},
  {product_id: 25, vitamin_id: 7},
  {product_id: 25, vitamin_id: 9},
  {product_id: 25, vitamin_id: 11},
  {product_id: 25, vitamin_id: 13},
  {product_id: 25, vitamin_id: 15},
  {product_id: 26, vitamin_id: 2},
  {product_id: 26, vitamin_id: 4},
  {product_id: 26, vitamin_id: 6},
  {product_id: 26, vitamin_id: 8},
  {product_id: 26, vitamin_id: 10},
  {product_id: 27, vitamin_id: 12},
  {product_id: 27, vitamin_id: 14},
  {product_id: 27, vitamin_id: 16},
  {product_id: 27, vitamin_id: 1},
  {product_id: 27, vitamin_id: 2},
  {product_id: 28, vitamin_id: 3},
  {product_id: 28, vitamin_id: 5},
  {product_id: 28, vitamin_id: 8},
  {product_id: 28, vitamin_id: 13},
  {product_id: 28, vitamin_id: 15},
  {product_id: 29, vitamin_id: 7},
  {product_id: 29, vitamin_id: 8},
  {product_id: 29, vitamin_id: 9},
  {product_id: 29, vitamin_id: 10},
  {product_id: 29, vitamin_id: 11},
  {product_id: 30, vitamin_id: 12},
  {product_id: 30, vitamin_id: 13},
  {product_id: 30, vitamin_id: 14},
  {product_id: 30, vitamin_id: 15},
  {product_id: 30, vitamin_id: 16},
  {product_id: 31, vitamin_id: 1},
  {product_id: 31, vitamin_id: 2},
  {product_id: 31, vitamin_id: 3},
  {product_id: 31, vitamin_id: 4},
  {product_id: 31, vitamin_id: 5},
  {product_id: 32, vitamin_id: 6},
  {product_id: 32, vitamin_id: 7},
  {product_id: 32, vitamin_id: 8},
  {product_id: 32, vitamin_id: 9},
  {product_id: 32, vitamin_id: 10},
  {product_id: 33, vitamin_id: 11},
  {product_id: 33, vitamin_id: 11},
  {product_id: 33, vitamin_id: 12},
  {product_id: 33, vitamin_id: 13},
  {product_id: 33, vitamin_id: 14},
  {product_id: 34, vitamin_id: 15},
  {product_id: 34, vitamin_id: 16},
  {product_id: 34, vitamin_id: 1},
  {product_id: 34, vitamin_id: 3},
  {product_id: 34, vitamin_id: 5},
  {product_id: 35, vitamin_id: 7},
  {product_id: 35, vitamin_id: 9},
  {product_id: 35, vitamin_id: 11},
  {product_id: 35, vitamin_id: 13},
  {product_id: 35, vitamin_id: 15},
  {product_id: 36, vitamin_id: 2},
  {product_id: 36, vitamin_id: 4},
  {product_id: 36, vitamin_id: 6},
  {product_id: 36, vitamin_id: 8},
  {product_id: 36, vitamin_id: 10},
  {product_id: 37, vitamin_id: 12},
  {product_id: 37, vitamin_id: 14},
  {product_id: 37, vitamin_id: 16},
  {product_id: 37, vitamin_id: 1},
  {product_id: 37, vitamin_id: 2},
  {product_id: 38, vitamin_id: 3},
  {product_id: 38, vitamin_id: 5},
  {product_id: 38, vitamin_id: 8},
  {product_id: 38, vitamin_id: 13},
  {product_id: 38, vitamin_id: 15},
  {product_id: 39, vitamin_id: 7},
  {product_id: 39, vitamin_id: 8},
  {product_id: 39, vitamin_id: 9},
  {product_id: 39, vitamin_id: 10},
  {product_id: 39, vitamin_id: 11},
  {product_id: 40, vitamin_id: 12},
  {product_id: 40, vitamin_id: 13},
  {product_id: 40, vitamin_id: 14},
  {product_id: 40, vitamin_id: 15},
  {product_id: 40, vitamin_id: 16},
  {product_id: 41, vitamin_id: 1},
  {product_id: 41, vitamin_id: 2},
  {product_id: 41, vitamin_id: 3},
  {product_id: 41, vitamin_id: 4},
  {product_id: 41, vitamin_id: 5},
  {product_id: 42, vitamin_id: 6},
  {product_id: 42, vitamin_id: 7},
  {product_id: 42, vitamin_id: 8},
  {product_id: 42, vitamin_id: 9},
  {product_id: 42, vitamin_id: 10},
  {product_id: 43, vitamin_id: 11},
  {product_id: 43, vitamin_id: 11},
  {product_id: 43, vitamin_id: 12},
  {product_id: 43, vitamin_id: 13},
  {product_id: 43, vitamin_id: 14},
  {product_id: 44, vitamin_id: 15},
  {product_id: 44, vitamin_id: 16},
  {product_id: 44, vitamin_id: 1},
  {product_id: 44, vitamin_id: 3},
  {product_id: 44, vitamin_id: 5},
  {product_id: 45, vitamin_id: 7},
  {product_id: 45, vitamin_id: 9},
  {product_id: 45, vitamin_id: 11},
  {product_id: 45, vitamin_id: 13},
  {product_id: 45, vitamin_id: 15},
  {product_id: 46, vitamin_id: 2},
  {product_id: 46, vitamin_id: 4},
  {product_id: 46, vitamin_id: 6},
  {product_id: 46, vitamin_id: 8},
  {product_id: 46, vitamin_id: 10},
  {product_id: 47, vitamin_id: 12},
  {product_id: 47, vitamin_id: 14},
  {product_id: 47, vitamin_id: 16},
  {product_id: 47, vitamin_id: 1},
  {product_id: 47, vitamin_id: 2},
  {product_id: 48, vitamin_id: 3},
  {product_id: 48, vitamin_id: 5},
  {product_id: 48, vitamin_id: 8},
  {product_id: 48, vitamin_id: 13},
  {product_id: 48, vitamin_id: 15},
  {product_id: 49, vitamin_id: 7},
  {product_id: 49, vitamin_id: 8},
  {product_id: 49, vitamin_id: 9},
  {product_id: 49, vitamin_id: 10},
  {product_id: 49, vitamin_id: 11},
  {product_id: 50, vitamin_id: 12},
  {product_id: 50, vitamin_id: 13},
  {product_id: 50, vitamin_id: 14},
  {product_id: 50, vitamin_id: 15},
  {product_id: 50, vitamin_id: 16},
  {product_id: 51, vitamin_id: 1},
  {product_id: 51, vitamin_id: 2},
  {product_id: 51, vitamin_id: 3},
  {product_id: 51, vitamin_id: 4},
  {product_id: 51, vitamin_id: 5},
  {product_id: 52, vitamin_id: 6},
  {product_id: 52, vitamin_id: 7},
  {product_id: 52, vitamin_id: 8},
  {product_id: 52, vitamin_id: 9},
  {product_id: 52, vitamin_id: 10},
  {product_id: 53, vitamin_id: 11},
  {product_id: 53, vitamin_id: 11},
  {product_id: 53, vitamin_id: 12},
  {product_id: 53, vitamin_id: 13},
  {product_id: 53, vitamin_id: 14},
  {product_id: 54, vitamin_id: 15},
  {product_id: 54, vitamin_id: 16},
  {product_id: 54, vitamin_id: 1},
  {product_id: 54, vitamin_id: 3},
  {product_id: 54, vitamin_id: 5},
  {product_id: 55, vitamin_id: 7},
  {product_id: 55, vitamin_id: 9},
  {product_id: 55, vitamin_id: 11},
  {product_id: 55, vitamin_id: 13},
  {product_id: 55, vitamin_id: 15},
  {product_id: 56, vitamin_id: 2},
  {product_id: 56, vitamin_id: 4},
  {product_id: 56, vitamin_id: 6},
  {product_id: 56, vitamin_id: 8},
  {product_id: 56, vitamin_id: 10},
  {product_id: 57, vitamin_id: 12},
  {product_id: 57, vitamin_id: 14},
  {product_id: 57, vitamin_id: 16},
  {product_id: 57, vitamin_id: 1},
  {product_id: 57, vitamin_id: 2},
  {product_id: 58, vitamin_id: 3},
  {product_id: 58, vitamin_id: 5},
  {product_id: 58, vitamin_id: 8},
  {product_id: 58, vitamin_id: 13},
  {product_id: 58, vitamin_id: 15},
  {product_id: 59, vitamin_id: 7},
  {product_id: 59, vitamin_id: 8},
  {product_id: 59, vitamin_id: 9},
  {product_id: 59, vitamin_id: 10},
  {product_id: 59, vitamin_id: 11}
])
puts "Create Product Vitamin"

User.create!([
  {email: "suga.seishi@gmail.com", name: "菅 誠志",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/1.jpg").open, role: "Farmer"},
  {email: "kotaro.yamamoto@gmail.com", name: "山本 浩太郎",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/2.jpg").open, role: "Farmer"},
  {email: "sugimoto.kazuya@gmail.com", name: "杉本 和也",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/3.jpg").open, role: "Farmer"},
  {email: "yuichi.hatano@gmail.com", name: "波多野 祐一",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/4.jpg").open, role: "Farmer"},
  {email: "maeda.naoo@gmail.com", name: "前田 尚雄",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/5.jpg").open, role: "Farmer"},
  {email: "masuichi.fukase@gmail.com", name: "深瀬 益一",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/6.jpg").open, role: "Farmer"},
  {email: "yoshiki.hyodome@gmail.com", name: "兵頭 芳樹",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/7.jpg").open, role: "Farmer"},
  {email: "shoichiro.yano@gmail.com", name: "矢野 昭一朗",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/8.jpg").open, role: "Farmer"},
  {email: "tadanori.misumi@gmail.com", name: "三隅 忠典",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/9.jpg").open, role: "Farmer"},
  {email: "tobushine.bayal@gmail.com", name: "トブシン バヤル",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/10.jpg").open, role: "Farmer"},
  {email: "daisuke.takeshima@gmail.com", name: "竹島 大祐",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/11.jpg").open, role: "Farmer"},
  {email: "mayuki.abe@gmail.com", name: "阿部 まゆき",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/12.jpg").open, role: "Farmer"},
  {email: "jiro.yamaguchi@gmail.com", name: "山口 次郎",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/13.jpg").open, role: "Farmer"},
  {email: "miyuki.nishioka@gmail.com", name: "西岡 守",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/14.jpg").open, role: "Farmer"},
  {email: "mai.kikuchi@gmail.com", name: "菊地 真衣",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/15.jpg").open, role: "Farmer"},
  {email: "yuji.nakamura@gmail.com", name: "中村 友哉",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/16.jpg").open, role: "Farmer"},
  {email: "junichi.takahashi@gmail.com", name: "高橋 潤一",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/17.jpg").open, role: "Farmer"},
  {email: "okada.hideaki@gmail.com", name: "岡田 英明",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/18.jpg").open, role: "Farmer"},
  {email: "rumi.ito@gmail.com", name: "伊藤 瑠美",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/19.jpg").open, role: "Farmer"},
  {email: "naho.hatazawa@gmail.com", name: "畑澤 菜穂",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/20.jpg").open, role: "Farmer"},
  {email: "hideyori.ando@gmail.com", name: "安藤 英利",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/21.jpg").open, role: "Farmer"},
  {email: "saka.shin@gmail.com", name: "坂神 翔",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/22.jpg").open, role: "Farmer"},
  {email: "shinta.kikuchi@gmail.com", name: "菊池 真太",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/23.jpg").open, role: "Farmer"},
  {email: "shinichi.hino@gmail.com", name: "日野 正一",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/24.jpg").open, role: "Farmer"},
  {email: "toshinori.ochi@gmail.com", name: "越智 貴則",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/25.jpg").open, role: "Farmer"},
  {email: "yuu.matsuzaki@gmail.com", name: "松崎 悠生",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/26.jpg").open, role: "Farmer"},
  {email: "kasuga.kazuki@gmail.com", name: "春日 和己",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/27.jpg").open, role: "Farmer"},
  {email: "tokunaga.teruaki@gmail.com", name: "徳永 光勇輝",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/28.jpg").open, role: "Farmer"},
  {email: "hiroyuki.kaneko@gmail.com", name: "金子 浩之",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/29.jpg").open, role: "Farmer"},
  {email: "genki.takeimori@gmail.com", name: "竹森 玄輝",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/30.jpg").open, role: "Farmer"},
  {email: "yoshitaka.kono@gmail.com", name: "河野 義孝",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/31.jpg").open, role: "Farmer"},
  {email: "osamu.nagasaka@gmail.com", name: "長坂 知洋",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/32.jpg").open, role: "Farmer"},
  {email: "kazuo.otsuka@gmail.com", name: "大塚 和生",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/33.jpg").open, role: "Farmer"},
  {email: "okura.junshi@gmail.com", name: "大倉 淳伸",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/34.jpg").open, role: "Farmer"},
  {email: "yukino.kamiko@gmail.com", name: "上甲 幸乃",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/35.jpg").open, role: "Farmer"},
  {email: "yusuke.saeki@gmail.com", name: "佐伯 祐介",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/36.jpg").open, role: "Farmer"},
  {email: "tamimi.yamauchi@gmail.com", name: "山内 いくみ",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/37.jpg").open, role: "Farmer"},
  {email: "tatsuya.mori@gmail.com", name: "森 達也",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/38.jpg").open, role: "Farmer"},
  {email: "masami.sasaki@gmail.com", name: "佐々木 政美",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/39.jpg").open, role: "Farmer"},
  {email: "inoka.megumi@gmail.com", name: "稲岡 メグミ",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/40.jpg").open, role: "Farmer"},
  {email: "mika@gmail.com", name: "祖母井 美香",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/41.jpg").open, role: "Farmer"},
  {email: "keiichi.inoka@gmail.com", name: "稲岡 慶一",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/42.jpg").open, role: "Farmer"},
  {email: "keizo.mizumoto@gmail.com", name: "水本 敬三",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/43.jpg").open, role: "Farmer"},
  {email: "kyoichi.tomoka@gmail.com", name: "知花 壮一郎",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/44.jpg").open, role: "Farmer"},
  {email: "hiro.saito@gmail.com", name: "斉藤 穂",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/45.jpg").open, role: "Farmer"},
  {email: "tomomi.ninomiya@gmail.com", name: "二宮 智義",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/46.jpg").open, role: "Farmer"},
  {email: "masashi.yamauchi@gmail.com", name: "山内 政志",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/47.jpg").open, role: "Farmer"},
  {email: "yoshihiro.katai@gmail.com", name: "片神 芳広",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/48.jpg").open, role: "Farmer"},
  {email: "kuwabara.araito@gmail.com", name: "桑原 侑汰",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/49.jpg").open, role: "Farmer"},
  {email: "fumiya.tamura@gmail.com", name: "田村 文弥",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/50.jpg").open, role: "Farmer"},
  {email: "takeshi.otagawa@gmail.com", name: "大亀 剛志",
    password: "123456", password_confirmation: "123456", avatar: Rails.root.join("app/assets/images/farmers/51.jpg").open, role: "Farmer"}
  ])
puts "Create Farmers"

Post.create!([
  {title: "農業しよう！妻の一言で移住して黄金メロン「黄美香(きみか)」を栽培", image: Rails.root.join("app/assets/images/posts/1.jpg").open,
    user_id: 13, content: "黄美香(きみか)メロンを栽培する、福井県あわら市 Fruits Park Okayuの岡田夫妻。
    宿泊業から農家に転身し、全く知らない土地で、フルーツを育て、地域の活性化を真剣に考えています。", product_id: 1},
  {title: "農家インタビュー　1房3万円?!小学生から研究した「夢のぶどう", image: Rails.root.join("app/assets/images/posts/2.jpg").open,
    user_id: 14, content: "有機JAS(オーガニック)認証のぶどう農家、山口県 亀の甲農園の三隅 忠典さん。
    農薬不使用では出来ないと言われてきた果樹の栽培に、果敢に挑み続けたその人生を伺ってきました。", product_id: 2},
  {title: "Kai誕生秘話。どうしてこんなバカなことを始めたのか？", image: Rails.root.join("app/assets/images/posts/3.jpg").open,
    user_id: 15, content: "「ネットゲームで野菜を作る」なぜそんなことを考えたのか？
    笑われても、バカにされても、ピーマンを投げられても諦めなかった、
    Kaiの生みの親・遠藤 忍が誕生秘話を語ります。", product_id: 3},
  {title: "農業しよう！妻の一言で移住して黄金メロン「黄美香(きみか)」を栽培", image: Rails.root.join("app/assets/images/posts/4.jpg").open,
    user_id: 16, content: "黄美香(きみか)メロンを栽培する、福井県あわら市 Fruits Park Okayuの岡田夫妻。
    宿泊業から農家に転身し、全く知らない土地で、フルーツを育て、地域の活性化を真剣に考えています。", product_id: 4},
  {title: "農家インタビュー　1房3万円?!小学生から研究した「夢のぶどう", image: Rails.root.join("app/assets/images/posts/5.jpg").open,
    user_id: 17, content: "有機JAS(オーガニック)認証のぶどう農家、山口県 亀の甲農園の三隅 忠典さん。
    農薬不使用では出来ないと言われてきた果樹の栽培に、果敢に挑み続けたその人生を伺ってきました。", product_id: 5},
  {title: "Kai誕生秘話。どうしてこんなバカなことを始めたのか？", image: Rails.root.join("app/assets/images/posts/6.jpg").open,
    user_id: 18, content: "「ネットゲームで野菜を作る」なぜそんなことを考えたのか？
    笑われても、バカにされても、ピーマンを投げられても諦めなかった、
    Kaiの生みの親・遠藤 忍が誕生秘話を語ります。", product_id: 6},
  {title: "農業しよう！妻の一言で移住して黄金メロン「黄美香(きみか)」を栽培", image: Rails.root.join("app/assets/images/posts/7.jpg").open,
    user_id: 19, content: "黄美香(きみか)メロンを栽培する、福井県あわら市 Fruits Park Okayuの岡田夫妻。
    宿泊業から農家に転身し、全く知らない土地で、フルーツを育て、地域の活性化を真剣に考えています。", product_id: 7},
  {title: "農家インタビュー　1房3万円?!小学生から研究した「夢のぶどう", image: Rails.root.join("app/assets/images/posts/8.jpg").open,
    user_id: 20, content: "有機JAS(オーガニック)認証のぶどう農家、山口県 亀の甲農園の三隅 忠典さん。
    農薬不使用では出来ないと言われてきた果樹の栽培に、果敢に挑み続けたその人生を伺ってきました。", product_id: 8},
  {title: "Kai誕生秘話。どうしてこんなバカなことを始めたのか？", image: Rails.root.join("app/assets/images/posts/9.jpg").open,
    user_id: 21, content: "「ネットゲームで野菜を作る」なぜそんなことを考えたのか？
    笑われても、バカにされても、ピーマンを投げられても諦めなかった、
    Kaiの生みの親・遠藤 忍が誕生秘話を語ります。", product_id: 9}
])
puts "Create Posts"

Post.all.each do |post|
  (1..9).each do
    comment = Comment.create user_id: 15, post_id: post.id,
      content: "豪雨被害は大丈夫でしたでしょうか?"
    Comment.create user_id: 16, post_id: post.id, parent_id: comment.id,
    content: "今晩は遅くなりすいません　愛媛県下の南予地方　
    肱川が氾濫して大変ですが　東予地区は大丈夫でしたが、
    この酷暑は農家の僕らは大変です！熱中症になりそうで、
    朝　夕方の作業でないとやばすぎです、むかご丸さん体調管理気をつけて下さい。"
  end
end
puts "Add Comment to Post"

Post.all.each do |post|
  Activity.create user_id: 17, post: post, activity_type: :like
  Activity.create user_id: 18, post: post, activity_type: :like
  Activity.create user_id: 19, post: post, activity_type: :like
  Activity.create user_id: 20, post: post, activity_type: :dislike
  Activity.create user_id: 21, post: post, activity_type: :dislike
end
puts "Add Like and Dislike to Post"
